DROP TABLE IF EXISTS User;
CREATE TABLE User(username VARCHAR(32) PRIMARY KEY, email VARCHAR(128), hash CHAR(60));
DROP TABLE IF EXISTS Urls;
CREATE TABLE Urls(url VARCHAR(256), short VARCHAR(32) PRIMARY KEY, username VARCHAR(32), timesVisited INTEGER, currentTime VARCHAR(32),FOREIGN KEY(username) REFERENCES User(username));
DROP TABLE IF EXISTS Tags;
CREATE TABLE Tags(tag VARCHAR(256), short VARCHAR(32), FOREIGN KEY(short) REFERENCES Urls(short));

